-- AlterTable
ALTER TABLE "shops" ADD COLUMN IF NOT EXISTS "category" TEXT;
ALTER TABLE "shops" ADD COLUMN IF NOT EXISTS "bank_name" TEXT;
ALTER TABLE "shops" ADD COLUMN IF NOT EXISTS "bank_account" TEXT;
ALTER TABLE "shops" ADD COLUMN IF NOT EXISTS "mfo" TEXT;
ALTER TABLE "shops" ADD COLUMN IF NOT EXISTS "oked" TEXT;
