// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// XAVFSIZLIK: API kalitlari --dart-define orqali berilishi kerak.
/// Development uchun fallback qiymatlar (Firebase public config).
///
/// Production build:
/// flutter build apk --release \
///   --dart-define=FIREBASE_WEB_API_KEY=xxx \
///   --dart-define=FIREBASE_ANDROID_API_KEY=xxx \
///   --dart-define=FIREBASE_IOS_API_KEY=xxx
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // --dart-define orqali berilgan kalitlar (release buildda majburiy)
  // Build: flutter build apk --dart-define=FIREBASE_WEB_API_KEY=xxx ...
  // Debug rejimda google-services.json dagi kalitlar fallback sifatida ishlatiladi
  static const String _webApiKeyEnv = String.fromEnvironment(
    'FIREBASE_WEB_API_KEY',
  );
  static const String _androidApiKeyEnv = String.fromEnvironment(
    'FIREBASE_ANDROID_API_KEY',
  );
  static const String _iosApiKeyEnv = String.fromEnvironment(
    'FIREBASE_IOS_API_KEY',
  );

  // Fallback: google-services.json / GoogleService-Info.plist dagi kalitlar
  // Bu kalitlar maxfiy emas — Firebase public client config
  static const String _androidApiKeyDefault =
      'AIzaSyC1SzjfYUHr1AkKNXVX6PmigFLAHclHVdQ';
  static const String _iosApiKeyDefault =
      'AIzaSyC1SzjfYUHr1AkKNXVX6PmigFLAHclHVdQ';
  static const String _webApiKeyDefault =
      'AIzaSyC1SzjfYUHr1AkKNXVX6PmigFLAHclHVdQ';

  static String get _webApiKey =>
      _webApiKeyEnv.isNotEmpty ? _webApiKeyEnv : _webApiKeyDefault;
  static String get _androidApiKey =>
      _androidApiKeyEnv.isNotEmpty ? _androidApiKeyEnv : _androidApiKeyDefault;
  static String get _iosApiKey =>
      _iosApiKeyEnv.isNotEmpty ? _iosApiKeyEnv : _iosApiKeyDefault;

  /// Build vaqtida Firebase kalitlari berilganligini tekshirish
  static void validateKeys() {
    if (_webApiKey.isEmpty || _androidApiKey.isEmpty || _iosApiKey.isEmpty) {
      throw StateError(
        'Firebase API kalitlari berilmagan!\n'
        'Build qilishda --dart-define parametrlarini bering:\n'
        '  --dart-define=FIREBASE_WEB_API_KEY=xxx\n'
        '  --dart-define=FIREBASE_ANDROID_API_KEY=xxx\n'
        '  --dart-define=FIREBASE_IOS_API_KEY=xxx',
      );
    }
  }

  static const String _projectId = 'topla-app-ef946';
  static const String _messagingSenderId = '541689366619';
  static const String _storageBucket = 'topla-app-ef946.firebasestorage.app';

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: _webApiKey,
        appId: '1:541689366619:web:c1fab85bd011362580d77e',
        messagingSenderId: _messagingSenderId,
        projectId: _projectId,
        authDomain: '$_projectId.firebaseapp.com',
        storageBucket: _storageBucket,
        measurementId: 'G-LYKWT8CWWX',
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: _androidApiKey,
        appId: '1:541689366619:android:41e773be3bffce7380d77e',
        messagingSenderId: _messagingSenderId,
        projectId: _projectId,
        storageBucket: _storageBucket,
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: _iosApiKey,
        appId: '1:541689366619:ios:1590258b8c7349e980d77e',
        messagingSenderId: _messagingSenderId,
        projectId: _projectId,
        storageBucket: _storageBucket,
        iosClientId:
            '541689366619-pbdh4qrpbm0ah87u6tcjht0ri9u0f2l4.apps.googleusercontent.com',
        iosBundleId: 'com.topla.toplaApp',
      );
}
